sudo: false
language: ruby

install: script/bootstrap
script: script/cibuild

matrix:
  include:
    - rvm: 2.6.0-preview1
    - rvm: 2.5.0
    - rvm: 2.4.3
    - rvm: 2.3.6
    - rvm: 2.2.9
    # JRuby
    - rvm: jruby-9.1.16.0

notfications:
  email: false
